Fixes for rmarkdown syntax errors in roxygen documentation code
Bioconductor/BiocManager pull request #113
Opened 2021-08-24 09:53 UTC by remlapmot

When reading your helpfiles I noticed that you had used a slightly incorrect syntax for your links. So I have fixed them with this PR. 

cheers
  Tom

2021-08-24 10:34 UTC, mtmorgan requested changes
Thanks for the changes. I agree with some but have reservations about others, as indicated in the comments in the code.

2021-08-24 10:34 UTC, mtmorgan commented on R/BiocManager-pkg.R
> +#' - [`BiocManager::install()`]: Install or update packages from
These are meant to be formatted as code giving the fully resolved command `BiocManager::install()`. The update formats this as `install()`. The reason for using the fully resolved command is that represents 'best practice' -- no ambiguity about which package `install()` comes from. 

Also, it seemed to me that it was more helpful to have the code-formatted fully resolved command, than to aim for the fully formatted command AND link, which would render in a confusing way.

This comment applies throughout.

2021-08-24 10:34 UTC, mtmorgan commented on R/BiocManager-pkg.R
> +#'   installed; see [`install.packages`].
The current formatting indicates how one is to get help on `install.packages` and so is informative across help systems, including terminal-based help systems that don't render links.

2021-08-24 10:34 UTC, mtmorgan commented on R/install.R
> +#' include: `lib.loc`, passed to [`old.packages()`] and used to
thanks, `` `link(...)()` `` changes look like the right thing to do...

2021-08-24 10:34 UTC, mtmorgan commented on R/install.R
> +#' [`BiocManager::repositories()`] returns the _Bioconductor_ and
I think this and similar, below, would be better as `` `BiocManager::repositories()` ``, without the link, following the logic in the comment above. Alternatively, I think they should be formatted with the fully resolved function `BiocManager::repositories()`, and with 'repositories' linked to the help page -- old-school `\code{BiocManager::\link{repositories}()}` I think.

2021-08-24 10:34 UTC, mtmorgan commented on R/valid.R
> +#' sufficient to update packages to their most recent version.
Please maintain indentation.

2022-11-17 14:29 UTC, LiNk-NY commented
Closed for inactivity.

2022-11-17 14:29 UTC, closed without merging